# Generated by Django 2.2.4 on 2021-05-24 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authors',
            name='notes',
            field=models.TextField(default='default'),
            preserve_default=False,
        ),
    ]
