# Generated by Django 2.2.4 on 2021-05-23 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ninjaapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojos',
            name='desc',
            field=models.TextField(default='hello'),
            preserve_default=False,
        ),
    ]
