# Generated by Django 2.2.4 on 2021-05-31 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('start_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thought',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thoughts_uploaded', to='start_app.User'),
        ),
        migrations.AlterField(
            model_name='thought',
            name='users_who_like',
            field=models.ManyToManyField(related_name='liked_thoughts', to='start_app.User'),
        ),
    ]
